export const dashboardData = {
  kpis: [
    {
      label: "Total Projects",
      value: "27",
      change: "Active client portfolio",
      trend: "up",
    },
    {
      label: "Total Ad Spend",
      value: "₹18.4L",
      change: "+12% portfolio investment",
      trend: "up",
    },
    {
      label: "Total Clicks",
      value: "284,321",
      change: "+15.8% qualified visits",
      trend: "up",
    },
    {
      label: "Total Conversions",
      value: "4,892",
      change: "+18.6% lead volume",
      trend: "up",
    },
    {
      label: "Average CTR",
      value: "5.42%",
      change: "+0.7 pts engagement",
      trend: "up",
    },
    {
      label: "Average ROAS",
      value: "4.8x",
      change: "Portfolio efficiency held",
      trend: "up",
    },
  ],
  trafficOverview: [
    { month: "Jul", traffic: 168200, leads: 2940 },
    { month: "Aug", traffic: 176840, leads: 3125 },
    { month: "Sep", traffic: 188420, leads: 3268 },
    { month: "Oct", traffic: 196880, leads: 3410 },
    { month: "Nov", traffic: 207640, leads: 3594 },
    { month: "Dec", traffic: 218920, leads: 3748 },
    { month: "Jan", traffic: 229560, leads: 3892 },
    { month: "Feb", traffic: 238740, leads: 4026 },
    { month: "Mar", traffic: 249880, leads: 4214 },
    { month: "Apr", traffic: 261940, leads: 4438 },
    { month: "May", traffic: 273680, leads: 4660 },
    { month: "Jun", traffic: 284321, leads: 4892 },
  ],
  projectPerformance: [
    {
      name: "AIMS Institutes",
      website: "https://theaims.ac.in/",
      status: "Scaling",
      monthlySpend: "₹3.2L",
      clicks: "48,620",
      conversions: "924",
      roas: "5.4x",
      growth: "+24%",
    },
    {
      name: "Chartered Housing",
      website: "https://charteredhousing.com/",
      status: "Active",
      monthlySpend: "₹2.6L",
      clicks: "36,480",
      conversions: "612",
      roas: "4.9x",
      growth: "+18%",
    },
    {
      name: "iVistaz Digital",
      website: "https://ivistaz.com/",
      status: "Active",
      monthlySpend: "₹1.8L",
      clicks: "29,740",
      conversions: "486",
      roas: "4.6x",
      growth: "+16%",
    },
    {
      name: "Nautilus Shipping",
      website: "https://nautilusshipping.com/",
      status: "Optimizing",
      monthlySpend: "₹2.1L",
      clicks: "27,920",
      conversions: "438",
      roas: "4.2x",
      growth: "+11%",
    },
    {
      name: "The Zuri",
      website: "https://www.thezurihotels.com/",
      status: "Scaling",
      monthlySpend: "₹3.4L",
      clicks: "52,180",
      conversions: "826",
      roas: "5.8x",
      growth: "+22%",
    },
    {
      name: "Tejasmaritime",
      website: "https://tejasmaritime.com/",
      status: "Active",
      monthlySpend: "₹1.5L",
      clicks: "19,660",
      conversions: "284",
      roas: "3.9x",
      growth: "+9%",
    },
    {
      name: "SunTec Group",
      website: "https://www.suntecgroup.com/",
      status: "Scaling",
      monthlySpend: "₹3.8L",
      clicks: "69,721",
      conversions: "1,322",
      roas: "6.1x",
      growth: "+27%",
    },
  ],
  googleAdsCampaigns: [
    {
      name: "Lead Generation Campaign",
      spend: "₹5.2L",
      clicks: "86,240",
      impressions: "15.4L",
      ctr: "5.60%",
      cpc: "₹6.03",
      conversions: "1,568",
    },
    {
      name: "Brand Search Campaign",
      spend: "₹2.8L",
      clicks: "48,120",
      impressions: "5.23L",
      ctr: "9.20%",
      cpc: "₹5.82",
      conversions: "742",
    },
    {
      name: "Remarketing Campaign",
      spend: "₹2.4L",
      clicks: "39,840",
      impressions: "4.74L",
      ctr: "8.40%",
      cpc: "₹6.02",
      conversions: "816",
    },
    {
      name: "Performance Max Campaign",
      spend: "₹5.6L",
      clicks: "72,460",
      impressions: "17.67L",
      ctr: "4.10%",
      cpc: "₹7.73",
      conversions: "1,324",
    },
    {
      name: "International Campaign",
      spend: "₹2.4L",
      clicks: "37,661",
      impressions: "11.77L",
      ctr: "3.20%",
      cpc: "₹6.37",
      conversions: "442",
    },
  ],
  recommendations: [
    {
      title: "Lead Generation Campaign increased conversions by 28%",
      description:
        "Conversion growth is strongest in education and real estate accounts. Maintain budget momentum while expanding high-intent keyword coverage.",
      priority: "High",
    },
    {
      title: "VV MSME achieved the highest ROAS at 6.2x",
      description:
        "The account is outperforming portfolio benchmarks through strong audience fit and efficient bidding. Use the same bid strategy pattern for similar B2B accounts.",
      priority: "Medium",
    },
    {
      title: "Chester's remarketing campaign reached 8.4% CTR",
      description:
        "Remarketing audiences are responding strongly to refreshed creative. Extend the creative test to hospitality and education segments.",
      priority: "Medium",
    },
    {
      title: "Portfolio spend increased 12% with stable efficiency",
      description:
        "Spend growth is being absorbed without loss of conversion efficiency. Continue scaling Performance Max and Lead Generation campaigns through the next cycle.",
      priority: "High",
    },
  ],
  recentActivity: [
    {
      title: "Budget pacing alert",
      description:
        "SunTec Group is pacing 9% above plan while maintaining a 6.1x ROAS.",
      time: "12 min ago",
    },
    {
      title: "Conversion quality improved",
      description:
        "AIMS Institutes produced 924 conversions with a 14% improvement in lead-to-enquiry quality.",
      time: "34 min ago",
    },
    {
      title: "Remarketing engagement spike",
      description:
        "Chester's remarketing CTR reached 8.4%, indicating strong audience recall.",
      time: "2 hours ago",
    },
    {
      title: "Portfolio efficiency stable",
      description:
        "Overall ROAS held at 4.8x while total media investment increased by 12%.",
      time: "Yesterday",
    },
  ],
};
