export const projects = [
  {
    id: 1,
    name: "iVistaz Digital",
    domain: "ivistaz.com",
    url: "https://ivistaz.com/",
    traffic: "42.6K",
    keywords: "2,420",
    seoScore: 92,
    healthScore: 94,
    status: "Active",
  },
  {
    id: 2,
    name: "Aarna Law",
    domain: "aarnalaw.com",
    url: "https://aarnalaw.com/",
    traffic: "18.9K",
    keywords: "1,126",
    seoScore: 84,
    healthScore: 82,
    status: "Active",
  },
  {
    id: 3,
    name: "SunTec Group",
    domain: "suntecgroup.com",
    url: "https://www.suntecgroup.com/",
    traffic: "35.4K",
    keywords: "2,014",
    seoScore: 88,
    healthScore: 90,
    status: "Active",
  },
  {
    id: 4,
    name: "Nautilus Shipping",
    domain: "nautilusshipping.com",
    url: "https://nautilusshipping.com/",
    traffic: "21.7K",
    keywords: "1,348",
    seoScore: 79,
    healthScore: 81,
    status: "Active",
  },
  {
    id: 5,
    name: "Tejas Maritime",
    domain: "tejasmaritime.com",
    url: "https://tejasmaritime.com/",
    traffic: "16.8K",
    keywords: "934",
    seoScore: 76,
    healthScore: 78,
    status: "Review",
  },
  {
    id: 6,
    name: "Zuri Hotels & Resorts",
    domain: "thezurihotels.com",
    url: "https://www.thezurihotels.com/",
    traffic: "28.3K",
    keywords: "1,492",
    seoScore: 67,
    healthScore: 69,
    status: "Review",
  },
  {
    id: 7,
    name: "AIMS Institutes",
    domain: "theaims.ac.in",
    url: "https://theaims.ac.in/",
    traffic: "24.5K",
    keywords: "1,705",
    seoScore: 73,
    healthScore: 75,
    status: "Active",
  },
  {
    id: 8,
    name: "Seslong",
    domain: "seslong.com",
    url: "https://seslong.com/",
    traffic: "9.8K",
    keywords: "612",
    seoScore: 64,
    healthScore: 66,
    status: "Paused",
  },
  {
    id: 9,
    name: "Chartered Housing",
    domain: "charteredhousing.com",
    url: "https://charteredhousing.com/",
    traffic: "14.2K",
    keywords: "846",
    seoScore: 81,
    healthScore: 83,
    status: "Review",
  },
];

export const projectStatuses = ["All", "Active", "Review", "Paused"];
